### ISSUE TITLE
Diagram Picture

### ISSUE THREAD

**Issue by danielebailo** [ltrani/EPOS_DCAT-AP#1]
Is it possible to have the following picture of the diagram
https://github.com/ltrani/EPOS_DCAT-AP/blob/master/EPOS_DCAT-AP.png
with a better quality?
We are having some troubles in understanding some of the relation connection just above dcat:distribution and rdfs:Resource

**Comment by ltrani** [comment]
Did you try downloading it?

**Comment by danielebailo** [comment]
yes. 
Zooming in helps a bit, but still there is some weird overlapping around "epos:theme" <<'recommended'>> label above rdfs:Resource.
Anyways, no hurries. 
Schema will be subject to updates: at the next update it might be updated so that connections are more clear. 
I was just using this issue as a reminder.
